apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment
  labels:
    app: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: kumarijessie/spring-app:153-429dddf1ce9840b6a8a6bea76ac103d7637a5c0d
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
